TMS Django/TMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import welcome
urlpatterns = [
    url(r'^$', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('supervisor/', include('supervisor.urls')),
]

TMS Django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.timesheet_view, name='timesheet_view'),
    path('profile/', views.profile_view, name='profile'),
    path('addtimesheet/', views.add_timesheet, name='addtimesheet'),
    path('edittimesheet/',views.edit_timesheet, name='edittimesheet'),
    path('logout/', views.logout_view, name='logout'),

    # Ajax calls

]

TMS Django/accounts/models.py
from django.db import models
from django.db.models.signals import post_save # we will now define signals so our Profile model will be
from django.dispatch import receiver           #automatically created/updated when we create/update User instances.
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_name = models.CharField(max_length=500)
    gender = models.CharField(max_length=10)
    job_position = models.CharField(max_length=20)
    salary = models.IntegerField()

    def __str__(self):
        return self.emp_name

class Project(models.Model):
    project_name = models.CharField(max_length=200)
    employees = models.ManyToManyField(Profile)

    def __str__(self):
        return self.project_name

class TimeSheet(models.Model):
    profile = models.ManyToManyField(Profile)
    emp_name = models.CharField(max_length=100, default='emp_name')
    date  = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    #project_name = models.CharField(max_length=100, default='project_name')
    def __str__(self):
        return self.emp_name + ' ' + self.project.project_name +' '+ str(self.date)

TMS Django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Profile, Project, TimeSheet
from django.contrib.auth.models import User
from django.http import JsonResponse
from datetime import datetime
import datetime
# Create your views here.
def login_view(request):
    print('in the login view')
    if request.method == 'POST':
        print('POST')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            data = {
                'logged_in': True,
                 'send_to' : 'accounts/profile.html'
            }
            username = User.objects.get(username=request.user.username)
            profile = Profile.objects.filter(user=username)
            return render(request, 'accounts/profile.html', {'profile': profile[0]})
            #return JsonResponse(data)
        else:
            return render(request, 'accounts/login.html', {'error': 'Username or Password is incorrect'})
    else:
        return render(request, 'accounts/login.html')



"""check if the user is is_authenticated
else render the login page
if logged in send him the projects he is involved in."""
def project_view(request):
    if request.user.is_authenticated:
        id = request.user.id
        emp_profile = Profile.objects.filter(user=id)[0] # get the profile object of the logged in user
        projects = emp_profile.project_set.all()         # use the profile object to get his projects
        return render(request, 'accounts/project.html', {'projects':projects})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# Checks if the user is logged in, else return him/her to login page
def timesheet_view(request):
    if request.user.is_authenticated:
        profile = Profile.objects.filter(user=request.user)[0]
        print(profile)
        timesheets = TimeSheet.objects.filter(profile=profile)
        print(timesheets)
        return render(request, 'accounts/timesheet.html', {'timesheets':timesheets})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

"""check if the user is logged in else return him to the login page
if request.method is GET send him the accounts/add_timesheet.html which has the form
to submit new TimeSheet
if request.method is POST write the timesheet object received to the database"""
def add_timesheet(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            project_id = request.POST.get('project_id')
            project = Project.objects.filter(id=project_id)[0]
            if request.POST['from'] >= request.POST['to']:
                return render(request, 'accounts/add_timesheet.html', {'project':project,'error':'start time should be less than end time'})
            profile = Profile.objects.filter(user=request.user)[0]
            added_timesheets = TimeSheet.objects.filter(profile=profile)
            #print(added_timesheets)
            for t in added_timesheets:
                a = datetime.datetime.strptime(request.POST['date'], "%Y-%m-%d").date()
                if t.date == a:
                    print(t.date, request.POST['date'])
                    if t.start_time <= datetime.datetime.strptime(request.POST['from'], '%H:%M').time()  < t.end_time or t.start_time < datetime.datetime.strptime(request.POST['to'], '%H:%M').time() <= t.end_time:
                        return render(request, 'accounts/add_timesheet.html', {'project':project,'error':'Conflit in adding new timesheet'})
            timesheet = TimeSheet()
            timesheet.date = request.POST['date']
            timesheet.start_time = request.POST['from']
            timesheet.end_time = request.POST['to']
            timesheet.project = Project.objects.filter(id=request.POST.get('project_id'))[0]
            timesheet.emp_name = request.user.username
            timesheet.save()
            #profile = Profile.objects.filter(user=request.user)[0]
            timesheet.profile.add(profile)
            timesheet.save()
            id = request.user.id
            print(timesheet.profile, request.user)
            emp_profile = Profile.objects.filter(user=id)[0] # get the profile object of the logged in user
            projects = emp_profile.project_set.all()         # use the profile object to get his projects
            return render(request, 'accounts/project.html', {'projects':projects})
        else:
            project_id = request.GET.get('project_id')
            project = Project.objects.filter(id=project_id)[0]
            return render(request, 'accounts/add_timesheet.html', {'project':project})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

"""check if the user is logged in else return him to the login page
if the request.method is GET, get the timesheet the user requested from database
check if the grace days are no more than 14 days. if more than 14 days send him/her to previous page
with an error messaage
if not then send him the requested timesheet to be edited."""
def edit_timesheet(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            timesheet_id = request.POST.get('timesheet_id')
            timesheet = TimeSheet.objects.filter(id=timesheet_id)[0]
            timesheet.user = request.user.username
            timesheet.date = request.POST['date']
            timesheet.start_time = request.POST['from']
            timesheet.end_time = request.POST['to']
            project = Project.objects.filter(project_name = request.POST.get('project_name'))[0]
            timesheet.project = project
            timesheet.save()
            profile = Profile.objects.filter(user=request.user)[0]
            timesheets = TimeSheet.objects.filter(profile=profile)
            return render(request, 'accounts/timesheet.html', {'timesheets':timesheets})
        else:
            timesheet_id = request.GET.get('timesheet_id')
            timesheet = TimeSheet.objects.filter(id=timesheet_id)[0]
            """if the requested timesheet's date to be edited is before 2 weeks
            then return the timesheets apge to user saying that, he canot edit that timesheet."""
            date = datetime.date.today()
            start_week = date - datetime.timedelta(date.weekday()+7)
            end_week = start_week + datetime.timedelta(14)
            if start_week <= timesheet.date < end_week:
                return render(request, 'accounts/edittimesheet.html', {'timesheet':timesheet})
            profile = Profile.objects.filter(user=request.user)[0]
            timesheets = TimeSheet.objects.filter(profile=profile)
            return render(request, 'accounts/timesheet.html', {'error':'You can\'t edit your two weeks past timesheet', 'timesheets':timesheets})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him to the login page
# get the profile object of the user and send it to him/her.
def profile_view(request):
    if request.user.is_authenticated:
        username = User.objects.get(username=request.user.username)
        profile = Profile.objects.filter(user=username)
        return render(request, 'accounts/profile.html', {'profile':profile[0]})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})



def logout_view(request):
    logout(request)
    return render(request, 'accounts/login.html', {'error':'logged out succesfully'})

TMS Django/accounts/templates/accounts/add_timesheet.html
{% extends 'accounts/base.html' %}
{% block content %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

  <body class="text-center">
    <div class="container">
    <div class="jumbotron">
        <fieldset class="fieldset" >
            <legend>Add Timesheet for {{project}}</legend>
    <form action="{% url 'accounts:addtimesheet' %}" method="post"  >
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next", value={{request.GET.next}}>
        {% endif %}
        <input type="hidden" name="project_id" value='{{project.id}}'>

        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">Date</label>
          <div class="col-md-3">
            <input type="date" class="form-control" name="date" id="inputEmail3" placeholder="Date">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">From</label>
          <div class="col-md-3">
            <input type="time" step="900" class="form-control" name="from" id="inputEmail3" placeholder="From">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">To</label>
          <div class="col-md-3">
            <input type="time" step="900" class="form-control" name="to" id="inputEmail3" placeholder="To">
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-8">
              {% if error %}
                <footer>{{error}}</footer>
              {% endif %}
              <br>
            <button type="submit" class="btn btn-primary">Add Timesheet</button>
              <a href="{% url 'accounts:timesheet_view' %}" class="btn btn-primary">View Timesheets</a>
          </div>
        </div>
    </form>
        </fieldset></div></div></body>
    <br>
    <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
{% endblock %}

TMS Django/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">
      <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://getbootstrap.com/docs/3.3/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Time Management System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href= "{% url 'accounts:profile'%}">Profile</a></li>
            <li><a href="{% url 'accounts:project' %}">View Projects</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">TimeSheet <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Manage TimeSheet</a></li>
                <li><a href="{% url 'accounts:project' %}">Add TimeSheet</a></li>
                <li><a href="{% url 'accounts:timesheet_view' %}">View TimeSheets</a></li>
              </ul>
            </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href = "{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span><b> Logout </b> </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                          <a href="{% url 'accounts:login'%}"><span class="glyphicon glyphicon-log-in"></span> Employee Login</a>
                        </li>
                        {% endif %}



           </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>


    {% block content %}
    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the application load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie10-viewport-bug-workaround.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.3.1.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }} /static/ajaxcalls.js"></script>
  </body>
</html>

TMS Django/accounts/templates/accounts/edittimesheet.html
{% extends 'accounts/base.html' %}
{% block content %}
  <body class="text-center">

    <div class="container">
    <div class="jumbotron">
        <fieldset class="fieldset" >
                <legend>Editing Timesheet for {{timesheet.project}}</legend>
    <form action="{% url 'accounts:edittimesheet' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value={{request.GET.next}}>
        {% endif %}
        <input type="hidden" name="timesheet_id" value={{timesheet.id}}>
        <input type="hidden" name="project_name" value='{{timesheet.project}}'>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">Date</label>
          <div class="col-md-3">
            <input type="date" class="form-control" name="date" id="inputEmail3" value="{{timesheet.date|date:"Y-m-d"}}" placeholder="Date">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">From</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="from" id="inputEmail3" value="{{timesheet.start_time|time:"h:i"}}" placeholder="From">
          </div>
        </div>
        <div class="form-group row">
          <label for="" class="col-md-3 col-form-label">To</label>
          <div class="col-md-3">
            <input type="time" class="form-control" name="to" id="inputEmail3" value="{{timesheet.end_time|time:"h:i"}}" placeholder="To">
          </div>
        </div>
        <div class="form-group row">
          <div class="col-md-8">
            <button type="submit" class="btn btn-primary">Add Timesheet</button>
          </div>
        </div>
        <!-- <input type="submit" name="Add Timesheet"> -->
    </form>
    <br>
                {% if error %}
        <footer style="color:red">{{error}}</footer>
    {% endif %}
        </fieldset>
    </div>
    </div>
    <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>

{% endblock %}

TMS Django/accounts/templates/accounts/home.html
{% extends "src.html" %}
{% block title %}
    Welcome page
{% endblock %}
{% block content %}
<div class="jumbotron">
      <div class="container">
        <h1>Hello, Django!</h1>
        <p>Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of Web development, so you can focus on writing your app without needing to reinvent the wheel. It’s free and open source.</p>
        <p><a class="btn btn-primary btn-lg" href="https://www.djangoproject.com/" role="button">Learn more &raquo;</a></p>
      </div>
</div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Pruthvi Sambu</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Shiva Supraj</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Sandeep Korrapati</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div>
<hr>

      <footer>
        <p>&copy; Company 2018</p>
      </footer>
{% endblock %}

TMS Django/accounts/templates/accounts/login.html
{% extends 'src.html' %}

{% block javascript %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <fieldset class="fieldset" >
            <legend>Login</legend>
            <div class="col-md-4">

        </div>
        <div class="col-md-4">
            <form action="{% url 'accounts:login' %}"  method="post">
                {% csrf_token %}
                <div class="form-group">
                <label for="username">User Name</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter UserName">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
                <button class="btn btn-lg btn-primary btn-block" id="check_login" type="submit">Log in</button>
            </form>
            {% if error %}
                  <footer style="color:red">{{error}}</footer>
                {% endif %}
        </div>
        <div class="col-md-4">

        </div>


        </fieldset>

    </div>
</div>
{% endblock %}

TMS Django/accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}
{% block content %}
{% csrf_token %}
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Employee Details</h5>
              <ul>
                  <li><strong>UserName:</strong> {{ profile.user }}</li>
                  <li><strong>Employee:</strong> {{ profile.emp_name }}</li>
                  <li><strong>Gender:</strong> {{ profile.gender }}</li>
                  <li><strong>Salary:</strong> {{ profile.salary }}</li>
              </ul>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
            <a href="{% url 'accounts:project' %}" class="btn btn-primary">View Projects</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

TMS Django/accounts/templates/accounts/project.html
{% extends 'accounts/base.html' %}
{% block content %}


    <body class="text-center">


      {% if projects %}
          {% for project in projects %}
             <form action="{% url 'accounts:addtimesheet' %}" method="get">
               <div class="container">
                  <div class="jumbotron">
                      <div class="row">
                        <div class="col-md-2">

                        </div>
                        <div class="col-md-8">
                          <div class="card w-75">
                            <div class="card-body">
                              <input type="hidden" name="project_id" value="{{ project.id }}">
                              <h3 class="card-title">{{ project.project_name }}</h3>
                              <label class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras accumsan ex quis enim luctus sodales.
                                Interdum et malesuada fames ac ante ipsum primis in faucibus. </label>
                              <input type="submit" class="btn btn-primary" value="Add Timesheet">
                                <a href="{% url 'accounts:timesheet_view' %}" class="btn btn-primary">View Timesheets</a>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-2">

                        </div>
                    </div>
                  </div>
               </div>
              </form>


        </body>

              <!-- <input type="radio" name = "project_id" value="{{ project.id }}">{{ project.project_name }}<br> -->
          {%endfor%}
              <!-- <input type="submit" value="Add Timesheet"> -->
      {%else%}
          <label style="color:red">You are not in any project currently</label>
      {%endif%}
{% endblock %}

TMS Django/accounts/templates/accounts/timesheet.html
{% extends 'accounts/base.html' %}
{% block content %}
<style>
th {
    text-align: center;
}
</style>
<body class="text-center">
<div class="container">
    <div class="jumbotron">
      <fieldset class="fieldset" >
            <legend>TimeSheets</legend>
        {% if timesheets %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Timesheet #</th>
                <th scope="col">project</th>
                <th scope="col">Date</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th></th>
              </tr>
              {% for timesheet in timesheets %}
              <form action="{% url 'accounts:edittimesheet' %}" method="get">
                <tr>
                  <td>{{timesheet.id}}</td>
                  <td name="project_name">{{ timesheet.project }}</td>
                  <td name="date"> {{ timesheet.date|date:"Y-m-d" }}</td>
                  <td name="from">{{timesheet.start_time|time:"h:i"}}</td>
                  <td name="to">{{ timesheet.end_time|time:"h:i" }}</td>
                  <input type="hidden" name="timesheet_id" value="{{timesheet.id}}">
                  <td><input type="submit" class="btn btn-primary" value="Edit Timesheet"></td>
                </tr>
              </form>
              {%endfor%}
            </thead>
          </table>
        {% else %}
          <label style="color:red">You donot have any time sheets available to view</label>
        {% endif %}
        {%if error%}
          <footer style="color:red">{{error}}</footer>
        {%endif%}
        <br>
        <a href="{% url 'accounts:logout' %}" class = "btn btn-danger" >Logout</a>
      </fieldset>
    </div>
</div>
    </body>
{% endblock %}

TMS Django/accounts/templates/accounts/view.html
{% extends 'accounts/base.html' %}
{% block content %}

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Time Management System</a>
      </div>
      <ul class="nav navbar-nav"> 
        <li><a href="{% url 'accounts:project' %}">View Projects</a></li>
        <li><a href="{% url 'accounts:timesheet_view' %}">View Timesheets</a></li>
        <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </ul>
    </div>
  </nav>


{% endblock %}