TMS Django/TMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import welcome
urlpatterns = [
    url(r'^$', welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('supervisor/', include('supervisor.urls')),
]

TMS Django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.timesheet_view, name='timesheet_view'),
    path('profile/', views.profile_view, name='profile'),
    path('addtimesheet/', views.add_timesheet, name='addtimesheet'),
    path('edittimesheet/',views.edit_timesheet, name='edittimesheet'),
    path('logout/', views.logout_view, name='logout'),

    # Ajax calls

]

TMS Django/supervisor/urls.py
from django.urls import path
from . import views


app_name = 'supervisor'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('project/', views.project_view, name='project'),
    path('timesheet/', views.get_timesheets_view, name='get_timesheets'),
    path('manageproject/', views.manageproject_view, name='manageproject'),
    path('edittimesheet/',views.get_emp_summaries_view, name='get_emp_summaries'),
    path('logout/', views.logout_view, name='logout'),
]

TMS Django/supervisor/models.py
from django.db import models
from accounts.models import Profile, Project
# Create your models here.
class Supervisor(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    sup_name = models.CharField(max_length=200, default='sup_name')
    projects = models.ManyToManyField(Project)
    def __str__(self):
        return self.sup_name

TMS Django/supervisor/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login, logout
from .models import Supervisor
from accounts.models import Profile, Project, TimeSheet
from django.contrib.auth.models import User
from datetime import datetime, date
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse
from django.http import HttpResponse
import json
from django.forms.models import model_to_dict
# Create your views here.

# This login_view gets the request and checks if the requested method is an get or postself.
# If the method is get return the login pageself.
# Else if post then check the credentials, if error then return to login page with message
#                                          else send the view page.

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        # Retrieve the profile object by using user and
        # use the profile object returned to check if the profile objects
        # is in the supervisor object. If the user is not None and returned
        # user_supervisor query set length is 1 then we login the user
        profile = Profile.objects.filter(user=user)
        if len(profile) == 0: return render(request, 'supervisor/login.html', {'error': 'Username or Password is incorrect'})
        profile = profile[0]
        user_supervisor = Supervisor.objects.filter(user=profile)
        if user is not None and (len(user_supervisor) == 1):
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            username = User.objects.get(username=request.user.username)
            profile = Profile.objects.filter(user=username)
            return render(request, 'supervisor/profile.html', {'profile': profile[0]})
        else:
            return render(request, 'supervisor/login.html', {'error': 'Username or Password is incorrect'})
    else:
        return render(request, 'supervisor/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'supervisor/login.html', {'error':'logged out succesfully'})

def project_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pass
        else:
            user = User.objects.get(username=request.user.username)
            profile = Profile.objects.filter(user=user)
            supervisor = Supervisor.objects.filter(user=profile[0])[0]
            projects = supervisor.projects.all()
            return render(request, 'supervisor/project.html', {'projects':projects})
    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})

# check if the user is logged in else return him login page
# else return the all the timesheets the user requested for a project
def get_timesheets_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
             pass
        else:
            project_id = request.GET['project_id']
            project = Project.objects.filter(id=project_id)[0]
            timesheets = TimeSheet.objects.filter(project=project)
            return render(request, 'supervisor/timesheet.html', {'timesheets':timesheets})
    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})


def get_emp_summaries_view(request):
    if request.method == 'POST':
        pass
    else:
        project_id = request.GET['project_id']
        project = Project.objects.filter(id=project_id)[0]
        timesheets = TimeSheet.objects.filter(project=project)
        emp_summaries = {}
        for timesheet in timesheets:
            if timesheet.emp_name in emp_summaries:
                emp_summaries[timesheet.emp_name] += datetime.combine(date.today(),timesheet.end_time) - datetime.combine(date.today(),timesheet.start_time)
                print(timesheet.emp_name,emp_summaries[timesheet.emp_name])
            else:
                emp_summaries[timesheet.emp_name] = datetime.combine(date.today(),timesheet.end_time) - datetime.combine(date.today(),timesheet.start_time)
                print(timesheet.emp_name,emp_summaries[timesheet.emp_name])
        return render(request, 'supervisor/Summaries.html',{'emp_summaries':emp_summaries,'project_name':project.project_name})

#check the user is logged in else return him to login page
# check if the request is POST else return the project requested
# if POST then remove/add the Selected employees from project

def manageproject_view(request):
    if request.user.is_authenticated:
        if request.method == 'POST' and request.is_ajax:
            # if the button clicked is delete_emp then delete the employees from
            # project else if add_emp then add employees to project
            print(request.POST)
            employees = request.POST
            if request.POST['perform'] == 'delete':
                print('delete_emp')
                employee_ids = request.POST.getlist('employees')
                project_id = request.POST['project_id']
                project = Project.objects.filter(id=project_id)[0]
                for e_id in employee_ids:
                    project.employees.remove(e_id)
                employees = Profile.objects.all()
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                employees_could_add = employees_could_add.values()
                project = Project.objects.filter(id=project_id)
                print(employees_could_add)
                res_emps = []
                for emp in employees_could_add:
                    res_emps.append(emp)
                #print(res_emps)
                res_emps1 = []
                employees_inproject = employees_inproject.values()
                for emp in employees_inproject:
                    res_emps1.append(emp)
                #print(res_emps1)
                data = {
                    'employees_could_add' : res_emps,
                    'employees_inproject' : res_emps1,
                    'project' : project.values()[0]
                }
                #print(data)
                return HttpResponse(json.dumps({'data': data}), content_type="application/json")
                #return render(request, 'supervisor/manageproject.html',{'project':project, 'employees_could_add':employees_could_add,'error':'Selected users are removed'})
            else: #if 'Add_emp' in request.POST:
                employee_ids = request.POST.getlist('employees_inproject')
                project_id = request.POST['project_id']
                project = Project.objects.filter(id=project_id)[0]
                for e_id in employee_ids:
                    emp = Profile.objects.filter(id=e_id)[0]
                    project.employees.add(emp)
                employees = Profile.objects.all()
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                print(1, employees_could_add)
                #project = Project.objects.filter(id=project_id)
                # convert the QuerySet of employee objects to another QuerySet of with dictionary values
                # store the result back in same variable
                # then create an empty list, append the each value in to the updateList
                # put the list in dictionary and send it to requested call
                employees_could_add = employees_could_add.values()
                project = Project.objects.filter(id=project_id)
                res_emps = []
                for emp in employees_could_add:
                    res_emps.append(emp)
                print(res_emps)
                res_emps1 = []
                employees_inproject = employees_inproject.values()
                for emp in employees_inproject:
                    res_emps1.append(emp)
                print(res_emps1)
                data = {
                    'employees_could_add' : res_emps,
                    'employees_inproject' : res_emps1,
                    'project' : project.values()[0]
                }
                #return JsonResponse(data)
                return HttpResponse(json.dumps({'data': data}), content_type="application/json")

        else:
            if 'manage_project' in request.GET:
                employees = Profile.objects.all()
                project_id = request.GET.get('project_id')
                project = Project.objects.filter(id=project_id)[0]
                employees_inproject =  project.employees.all()
                employees_could_add =  employees.difference(employees_inproject)
                return render(request, 'supervisor/manageproject.html', {'project':project, 'employees_could_add':employees_could_add})

    else:
        return render(request, 'supervisor/login.html', {'error': 'Login to access the page'})

def profile_view(request):
    if request.user.is_authenticated:
        username = User.objects.get(username=request.user.username)
        profile = Profile.objects.filter(user=username)
        return render(request, 'supervisor/profile.html', {'profile':profile[0]})
    else:
        return render(request, 'accounts/login.html', {'error': 'Login to access the page'})

TMS Django/supervisor/templates/supervisor/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">
      <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

    <title>
        {% block title %}
        {% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="https://getbootstrap.com/docs/3.3/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Time Management System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'welcome' %}">Home</a></li>
            <li><a href= "{% url 'supervisor:profile'%}">Profile</a></li>
            <li><a href="{% url 'supervisor:project' %}">Projects Supervising</a></li>

          </ul>
            <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href = "{% url 'supervisor:logout' %}"><span class="glyphicon glyphicon-log-out"></span><b> Logout </b> </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                          <a href="{% url 'supervisor:login'%}"><span class="glyphicon glyphicon-log-in"></span> Employee Login</a>
                        </li>
                        {% endif %}



           </ul>

        </div><!--/.navbar-collapse -->
      </div>
    </nav>


    {% block content %}
    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the application load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/3.3/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.3.1.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }} /static/ajaxcalls.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }} /static/supervisor.js"></script>
  </body>
</html>

TMS Django/supervisor/templates/supervisor/login.html
{% extends 'src.html' %}

{% block javascript %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <fieldset class="fieldset" >
            <legend>Login</legend>
            <div class="col-md-4">

        </div>
        <div class="col-md-4">
          <form action="{% url 'supervisor:login' %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="username">User Name</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter UserName">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
                <button class="btn btn-lg btn-primary btn-block" id="check_login" type="submit">Log in</button>
            </form>
            {% if error %}
                  <footer style="color:red">{{error}}</footer>
                {% endif %}
        </div>
          <div class="col-md-4">

          </div>
    </fieldset>

    </div>
</div>
{% endblock %}

TMS Django/supervisor/templates/supervisor/manageproject.html
{% extends 'supervisor/base.html' %}
{% block content %}
<style>
input[type="checkbox"] {
    width: 20px;
    height: 20px;
    vertical-align: bottom;
}
label.checkbox {
    vertical-align: top;
    line-height: 24px;
    margin: 2px 0;
    height: 24px;
}
</style>

  <body>
        <div class="container">
        <div class="jumbotron">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">{{ project.project_name }}</h3>
    <div class="container" >
      <div class="row" >
        <div class="col-xs-6" >
          <form action="{% url 'supervisor:manageproject' %}" id="my_form1" method="post">
            {% csrf_token %}
            <input type="hidden" name="project_id", value={{project.id}}>
            <table class="table" id = "change_form1">
              {% for employee in employees_could_add.all %}
              <tr>
                <td><label><input type="checkbox" name="employees_inproject" value="{{employee.id}}" style="align:left"> {{employee}}</label></td>
              </tr>
              {% endfor%}
              <tr>
                <td><button  class="btn btn-primary" name="Add_emp" value = "Add" type="submit">Add Employees</button></td>
              </tr>
            </table>
          </form>
        </div>
        <div class="col-xs-6">
          <form action="{% url 'supervisor:manageproject' %}" id="my_form2" method="post">
            {% csrf_token %}
            <input type="hidden" name="project_id", value={{project.id}}>
            <table class="table" id = "change_form2">
            {% for employee in project.employees.all %}
              <tr>
                <td><input type="checkbox" name="employees" value="{{employee.id}}"> {{employee}}</td>
              </tr>
            {% endfor%}
            <tr>
              <td><button  class="btn btn-danger" name="Delete_emp" value="delete" type="submit">Delete</button></td>
            </tr>
            </table>
          </form>
        </div>
      </div>
    </div>
              </div>
            </div>
        </div>
        </div>
  </body>
<div class="text-center"><a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a></div>


{% endblock %}

TMS Django/supervisor/templates/supervisor/profile.html
{% extends "supervisor/base.html" %}
{% block content %}
{% csrf_token %}
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Employee Details</h5>
              <ul>
                  <li><strong>UserName:</strong> {{ profile.user }}</li>
                  <li><strong>Employee:</strong> {{ profile.emp_name }}</li>
                  <li><strong>Gender:</strong> {{ profile.gender }}</li>
                  <li><strong>Salary:</strong> {{ profile.salary }}</li>
              </ul>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

TMS Django/supervisor/templates/supervisor/project.html
{% extends 'supervisor/base.html' %}
{% block content %}

    <body class="text-center">
      {% if projects %}
          {% for project in projects %}
      <div class="container">
        <div class="jumbotron">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">{{ project.project_name }}</h3>
                <label class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras accumsan ex quis enim luctus sodales.
                  Interdum et malesuada fames ac ante ipsum primis in faucibus. </label>
                  <div class="row">
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:manageproject' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name = "manage_project" value="Manage Project">
                      </form>
                    </div>
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:get_emp_summaries' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name="get_emp_summaries" value="Generate Summaries">
                      </form>
                    </div>
                    <div class="col-sm-4">
                      <form action="{% url 'supervisor:get_timesheets' %}" method="get">
                         <input type="hidden" name="project_id" value="{{ project.id }}">
                         <input type="submit" class="btn btn-primary" name="get_timesheets" value="Get Timesheets">
                      </form>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      {%endfor%}

      {%else%}
        <label style="color:red">You are not in any project currently</label>
      {%endif%}
      <br>
      <a href="{% url 'supervisor:logout' %}" class="btn btn-danger">Logout</a>
{% endblock %}

TMS Django/supervisor/templates/supervisor/summaries.html
<!doctype html>
{% extends 'supervisor/base.html' %}
{% load staticfiles  %}


<html lang="en">

{% block content %}
<style>
th {
    text-align: center;
}
</style>
<body class="text-center">
<div class="container">
    <div class="jumbotron">
      <fieldset class="fieldset" >
            <legend>TimeSheet for Employees working on {{project_name}}</legend>
      {% if emp_summaries %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Employee Name</th>
            <th scope="col">Hours Worked</th>
          </tr>
        </thead>
        {% for key,value in emp_summaries.items %}
        <tr>
          <td>{{key}}</td>
          <td>{{value}}</td>
        </tr>
        {%endfor%}
      </table>
      {%else%}
       <label style="color:red">There are not Timesheets available</label>
      {%endif%}

      </fieldset>
    </div>
</div>
<a href="{% url 'supervisor:logout' %}" class="btn btn-danger">Logout</a>
</body>
{% endblock %}
</html>

TMS Django/supervisor/templates/supervisor/timesheet.html
{% extends 'supervisor/base.html' %}
{% load staticfiles  %}


<html lang="en">

{% block content %}
<style>
td, th{
  padding: 5px
}
</style>
<body class="text-center">
<div class="container">
    <div class="jumbotron">
      <fieldset class="fieldset" >
            <legend>TimeSheet of Employees</legend>
        <table>
        <tbody>
            <tr>
                <td>From Date:</td>
                <td><input class="form-control" name="min" id="min" type="date"></td>
            </tr>
            <tr>
                <td>To Date:</td>
                <td><input  class="form-control" name="max" id="max" type="date"></td>
                <td><button onclick="filter_by_date()" type="button" name="button" class = "btn btn-success">Go</button></td>
            </tr>
            <tr>
              <td>Search by name</td>
              <td> <input class="form-control" type="text" name="" id="input_by_name" onkeyup="search_by_name()" value=""> </td>
            </tr>
        </tbody>
      </table>
        {% if timesheets %}
          <table class="table table-hover" id = example>
            <thead>
              <tr>
                <th scope="col">Timesheet #</th>
                <th scope="col">Employee Name</th>
                <th scope="col">Project</th>
                <th scope="col">Date</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
              </tr>
              {% for timesheet in timesheets %}
              <form action="" method="get">
                <tr>
                  <td name="timesheet_id">{{timesheet.id}}</td>
                  <td name="emp_name">{{timesheet.emp_name}}</td>
                  <td name="project_name">{{ timesheet.project }}</td>
                  <td name="date"> {{ timesheet.date|date:"Y-m-d" }}</td>
                  <td name="from">{{timesheet.start_time|time:"h:i"}}</td>
                  <td name="to">{{ timesheet.end_time|time:"h:i" }}</td>
                  <input type="hidden" name="timesheet_id" value="{{timesheet.id}}">
                </tr>
              </form>
              {%endfor%}
            </thead>
          </table>
        {% else %}
          <h2>You donot have any time sheets available to view</h2>
        {% endif %}
        {%if error%}
          <h2>{{error}}</h2>
        {%endif%}
        </fieldset>
    </div>
</div>
</body>

        <br>
        <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a>
{% endblock %}
  </html>

TMS Django/supervisor/templates/supervisor/view.html
<!doctype html>

{% load staticfiles  %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <title>TMS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <a href="{% url 'supervisor:project' %}">View Projects you are supervising</a>
    <br>
    <a href="{% url 'accounts:timesheet_view' %}">View Timesheets</a>
    <br>
    <a href="{% url 'accounts:profile' %}">Profile</a>
    <br>
    <a href="{% url 'supervisor:logout' %}">Logout</a>
</html